//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.XinJiang3gCard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XinJiang3gCardHttpRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XinJiang3gCardHttpRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.XinJiang3gCard.XinJiang3gCardHttpRes", typeof(XinJiang3gCardHttpRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 890乌鲁木齐
        ///891昌吉
        ///893石河子
        ///892奎屯
        ///952塔城
        ///899克拉玛依
        ///898伊犁
        ///951博乐
        ///953阿勒泰
        ///894吐鲁番
        ///900哈密
        ///895巴音郭楞
        ///896阿克苏
        ///897喀什
        ///955和田
        ///954克孜勒苏.
        /// </summary>
        public static string Attribution {
            get {
                return ResourceManager.GetString("Attribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CITY_MAP&quot;:{&quot;110100&quot;:[{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110101&quot;,&quot;DISTRICT_NAME&quot;:&quot;东城区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110102&quot;,&quot;DISTRICT_NAME&quot;:&quot;西城区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110105&quot;,&quot;DISTRICT_NAME&quot;:&quot;朝阳区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110106&quot;,&quot;DISTRICT_NAME&quot;:&quot;丰台区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110107&quot;,&quot;DISTRICT_NAME&quot;:&quot;石景山区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110108&quot;,&quot;DISTRICT_NAME&quot;:&quot;海淀区&quot;},{&quot;CITY_CODE&quot;:&quot;110100&quot;,&quot;DISTRICT_CODE&quot;:&quot;110109&quot;,&quot;DISTRICT_NAME&quot;:&quot;门头沟区 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
    }
}
